# Use postgres/example user/password credentials

services:

  # --- Application Infrastructure ---

  db:
    image: postgres:15
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: ntvs_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  api:
    build:
      context: ./code
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: ntvs_db
      DB_USER: admin
      DB_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # --- Airflow Orchestration ---

  airflow-db:
    image: postgres:15
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U airflow" ]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    image: apache/airflow:2.7.1
    depends_on:
      airflow-db:
        condition: service_healthy
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db/airflow
    command: >
      bash -c "airflow db migrate &&  airflow users create --username admin --password admin --firstname Ryann --lastname User --role Admin --email admin@example.com"

  airflow-webserver:
    image: apache/airflow:2.7.1
    restart: always
    depends_on:
      airflow-db:
        condition: service_healthy
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _PIP_ADDITIONAL_DEPENDENCIES=requests beautifulsoup4 psycopg2-binary python-dotenv
    volumes:
      - ./dags:/opt/airflow/dags
      - ./code:/opt/airflow/code
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    ports:
      - 8081:8080
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.7.1
    restart: always
    depends_on:
      airflow-db:
        condition: service_healthy
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _PIP_ADDITIONAL_DEPENDENCIES=requests beautifulsoup4 psycopg2-binary python-dotenv
      - DB_HOST=db
      - DB_NAME=ntvs_db
      - DB_USER=admin
      - DB_PASSWORD=example
    volumes:
      - ./dags:/opt/airflow/dags
      - ./code:/opt/airflow/code
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    command: scheduler
